### PR TITLE
WIP: Build with pre-compiled wxWidgets

### PR DESCRIPTION
**Pull request by hmaarrfk**
This isn't the easiest since their Phoenix project assumes that the whole wxWidgets tree exist in their directory.

However, it seems that there is hope in synchronizing both projects since they recently updated to 3.2 (which I just finished compiling for all platforms on conda-forge)

https://github.com/wxWidgets/Phoenix/pull/2198

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
NOTE:

This may be a Bad Idea™️

My info could be WAY out of date, but (way) back in the day, wxPython on LInux systems crashed hard sometimes, when the user made a pure-Python error.

I think the issue is that the "impedance mismatch" between Python's dynamic typing and C++'s static typing, illegal calls could be made into the C++ code. The solution is to build the wx libs in a way that they can recover from this better (debug mode? something else?).

In any case, as a rule, wxPython probably should not be using the wx libraries built in the same way as C++ applications.

It's also critical that the Python bindings are using teh exact same version, which might be hard to maintain if they are separately built.

**Comment by hmaarrfk** [comment]
> My info could be WAY out of date, but (way) back in the day, wxPython on LInux systems crashed hard sometimes, when the user made a pure-Python error.

That sounds like a good thing to worry about, but it sounds also that this should be something worried about upstream. There used to be many rough edges with python + c integration in the past. I'm not sure how far back you are speaking, but this hsouldn't happen anymore.

> In any case, as a rule, wxPython probably should not be using the wx libraries built in the same way as C++ applications.

This is generally true when users do not take care of matching the ABI between different compilations. Using conda-forge, you do guarantee that. Using the precompiled libraries is like creating a checkpoint in the build process.

> It's also critical that the Python bindings are using teh exact same version, which might be hard to maintain if they are separately built.

Conda (forge) does try to handle this by pinning the runtime dependencies based on the compile time versions.

**Comment by hmaarrfk** [comment]
They apparently released a new version 2 days ago. it might be worthwhile to revive this effort now. there seemed to be a bit of a lag upstream before.

**Comment by ChrisBarker-NOAA** [comment]
Yes -- the new release is why I'm paying attention this this now :-)

Ideally the first step is to get that to build -- I took a quick look and couldn't see why it's failing.

> This is generally true when users do not take care of matching the ABI between different compilations. Using conda-forge, you do guarantee that.

It really is something beyond the ABI -- trust me on this :-) or at least it was, but we need to make absolutely sure that the builds are the same before separating them.

Also -- I think wxPYthon has been known to patch wx specifically for the bindings, and those patches are probably headed upstream, but again, we need to make sure.

**Comment by hmaarrfk** [comment]
You should definitely feel free to ignore this PR and push through with the other release.

**Comment by pauldmccarthy** [comment]
This was done in #122

**Pull request closed without merging**
