### PR TITLE
Python should include lzma

### PR DESCRIPTION
**Pull request by peterjc**
wxpython shouldn't need backports.lzma at all as Python 3.3 onwards ought to include it.

Cross reference discussion here: https://github.com/conda-forge/backports.lzma-feedstock/pull/34

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Comment by dopplershift** [comment]
@ocefpaf If this were merged, I think that would unstick wxpython on the 3.10 migration.

**Comment by ocefpaf** [comment]
Let's close and reopen to toggle the CIs and make them run again. This one scaped me and it has gone stale, sorry about that.

**Comment by dopplershift** [comment]
@ocefpaf This still passes! 🎉

**Comment by peterjc** [comment]
That's lucky - I had forgotten about this issue too.

**Comment by ocefpaf** [comment]
Thanks @peterjc for the PR and @dopplershift for the ping!

**Pull request merged**
