### PR TITLE
wxPython 4.2.0 build fixes

### PR DESCRIPTION
**Pull request by ndevenish**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The automated PR #84 for 4.2.0 ran into a few issues with patching the source in places where it had been updated. This is an attempt to clean that up so that we can have a build working with python 3.10 (https://github.com/wxWidgets/Phoenix/issues/2128 appears to be where it was published).

### CODE REVIEW

**Comment by ndevenish** [comment]
Note (from the commit) that this later commit https://github.com/wxWidgets/Phoenix/commit/2e9169effa9abf14f34f8436a791b8829eea7774 removes the attrdict3 dependency from everything but windows; attrdict3 appears to be a separate project and only the original is currently present on conda-forge: https://github.com/conda-forge/attrdict-feedstock

**Comment by ndevenish** [comment]
No, it seems to require a newer `attrdict3`. I'll continue working towards this (including submitting new package) next week.

**Comment by ChrisBarker-NOAA** [comment]
hmm -- attrdict3 is a fork of attrdict, with no indication (that I can find) as to why it was forked, and what the differences are :-(

Though the original has been archived, and not touched in 4 yrs, as far as I can tell :-(

Seems the only difference is updated collections importing for python 3.10. Oh well.

**Comment by ndevenish** [comment]
I asked in the conda-forge gitter whether in this case it’d be better to add a v3 to the attrdict feedstock, but got no response, so I’ll submit a new feedstock

**Comment by ChrisBarker-NOAA** [comment]
Yeah, that's probably the way to go -- without the original author signing off, it's best not so use the same name :-(

**Comment by ndevenish** [comment]
Ah, I did some digging. It's forked and renamed, but the only difference is fixing import references for python 3.10. This is probably worth considering just patching. Otherwise looks like mac patches need to be tweaked.

**Comment by ChrisBarker-NOAA** [comment]
well, the original project doesn't seem to be maintained, though I suppose we don't know if the fork will be maintained either :-( -- ideally wxPython would vendor it, but this is where we are at now. Your call.

I might be able to help with the Mac -- but I can't make any sense of the logs -- they don't seem to end with a failure, so any hints as to what to look at?

**Comment by melund** [comment]
@ndevenish Could you try to pull from master and restart the build here? The logs have expired. I think updating to wxpython 4.2 is important to get python 3.11 support. 

Otherwise, maybe we could leave out osx support for now. My python concern is getting it working on windows.

**Comment by melund** [comment]
It fails with: 
```
checking for SDK directory /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk... exists
configure: error: in `/Users/runner/miniforge3/conda-bld/wxpython_1667812166513/work/build/wxbld':
configure: error: building C++ programs doesn't work, try using --with-macosx-sdk with a different SDK or omitting it entirely to use the default one.
See `config.log' for more details
checking if C compiler (x86_64-apple-darwin13.4.0-clang -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10) works with SDK/version options... Error running configure
``` 

Maybe the patch to the macos-sdk is no longer needed with wxpython 4.2??

**Comment by ndevenish** [comment]
Unfortunately didn't seem to make a difference, so maybe it isn't necessary but also not what is causing the issue. I'm going to try to get the config.log.

**Comment by ndevenish** [comment]
The frustrating part is that this part of the build works fine on my machine locally.

**Comment by ndevenish** [comment]
Success:
```
clang-14: error: the clang compiler does not support '-march=core2'
```

**Comment by ndevenish** [comment]
Also to solve; MacOS builds now ignore system (e.g. conda-forge supplied) versions  of libjpeg, libpng, libtiff and pcre: https://github.com/wxWidgets/Phoenix/blob/wxPython-4.2.0/buildtools/build_wxwidgets.py#L326-L329

**Comment by melund** [comment]
>  Success:

@ndevenish . Great. It seems arm osx builds are still failing. I vote for adding `skip: true [osx-arm64]` to the build section of `meta.yaml`. Then we can fix it later. I really need the python 3.11 builds :)

Also, remember to undo the changes to: `[.azure-pipelines/*](https://github.com/ndevenish/wxpython-feedstock/tree/main/.azure-pipelines)` files.

**Comment by ndevenish** [comment]
I'll have another attempt today, otherwise will do that, yes. Once that is done we'll still need to wait for one of the actual maintainers to merge, however.

Also it looks like this won't directly make 3.11 work, https://github.com/conda-forge/wxpython-feedstock/pull/89 seems to have failed with something that looks like a sip/gtk issue? Do you know that this version of wxPython is what is holding that up?

**Comment by melund** [comment]
> Also it looks like this won't directly make 3.11 work, https://github.com/conda-forge/wxpython-feedstock/pull/89 seems to have failed with something that looks like a sip/gtk issue? 

I think that will be solved by upgrading to wxpython 4.2. So once this is fixed, then hopefully the migration bot will pick it up and add python 3.11 support.

**Pull request merged**
