### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by ocefpaf**
Just testing...

### CODE REVIEW

**Comment by nicoddemus** [comment]
ping @ocefpaf, probably forgot about this PR. 😁

**Comment by ocefpaf** [comment]
> ping @ocefpaf, probably forgot about this PR.

Indeed I did :grimacing: 

I'll try to get back to it next week. (Unless you want to take it over :wink:)

**Comment by nicoddemus** [comment]
I will pass for now, never built wxPython before hehehe

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Oh the irony! Linux was the only passing one b/c of the `yum_requirements.txt` but now that we are no longer using it is the only one failing :smile:

I'm inclined to merge this to get a OS X and Windows package in the channel and open an issue for the Linux one.

**Comment by ocefpaf** [comment]
I'll fix try to fix the Linux builds in another PR. Let's "cash in" Windows and OS X for now.

**Pull request merged**
