### PR TITLE
install wxwidgets same on all platforms (include headers and libs in lib/)

### LINKED ISSUE #28: Installing wxWidgets headers and *.lib
Issue: Feature Request/Discussion

Our C++/Python code uses mostly wxWidgets with few windows/panels done with wxPython, we are moving towards using wxPython more. In addition we want to used conda to manage our library dependencies, most of our other dependencies are already in conda forge. 

In order for this pie to work it is impotent to use same wxWidgets libraries in C++ part as one used in wxPython on python side. So the question is: is there interest to add wxWidgets headers and *.lib to wxpython package?

And another question is how to implement it best. I have started playing with it and debating should I update build.py or create bld.bat? There is also possibility to use post-linking script, but according to docs this script is not desired and should only operate on installed files.

Thanks,
Nikolay

### PR DESCRIPTION
**Pull request by timsnyder**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.
* [ ] Determine why the `win-64` packages are so much larger and whether we want to tweak this more before merging.

Fixes #28 by using `--no_magic` for build and install of Windows and macOS like it has been being used for linux.

### CODE REVIEW

**Comment by timsnyder** [comment]
Well, looks like I need some RPATH arguments for macos that I'm missing.

**Comment by timsnyder** [comment]
I'm also seeing that the wxpython `build.py` doesn't obey `--no_magic` for Windows.  I'm going to ask the wxpython folks about this and open a new PR after I get that straightened out.

**Comment by timsnyder** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
LGTM, merge?

**Comment by timsnyder** [comment]
@ocefpaf , I tweaked the new patchfile I added to remove changes to `cmd_install_wx()` since I'm no longer running `build.py install_wx` on Windows. I decided that using @nsimakov's `install_wxwidgets.bat` to install the wxWidgets headers and libraries is the best way to do that for Windows right now.  I merged his script from #29 into this PR and made a few updates (to remove hardcoding of the wxWidgets `lib/` subdirectory since it has changed from `lib/vc140_dll` to `lib/vc140_x86_dll` and will change again when we update to using vc<newer> soon).

I've notified the wxpython community about how we're now going to package for Windows and MacOS in https://discuss.wxpython.org/t/including-wxwidgets-headers-in-windows-and-macos-builds/34471/5 

Package Size Changes From This PR:
 Platform | Old Size | New Size
---------|----------|-----------
MacOS | 15.5 MB | 16.9 MB
win-64 | 14.9 MB | 54.7 MB

NOTE: linux packages are unchanged by this PR because they have been including the wxWidgets and libraries for as long as I can remember (and I built them like that before conda-forge).

The last thing that I might consider doing is to optimize the size of the new Windows packages.  @nsimakov's `install_wxwidgets.bat` includes all of the `.lib` files that wxWidgets creates.  However, many of them also have DLL libraries that are copied over.  I think that we could optimize the script to only include the `.lib` files that do not have DLL files.

**Comment by timsnyder** [comment]
I'm going to do some quick-and-dirty analysis of why the win-64 packages are so much bigger once we include the wxWidgets headers and libs.

**Comment by timsnyder** [comment]
Looks like most of the size increase comes from the `.pdb` files (symbol information for debugging on Windows) and duplicated `.lib` files (ones that have corresponding `.dll`).

I'm going to drop the `.pdb` files.  They could be added in a separate 'debug' version of the package but I don't think they will be needed by most users and the other platforms don't supply debug information in the wxpython package.  The installed size of the new Windows package is ~276MB, removing the `.pdb` files will reduce it to ~111MB.  Since I'm less certain about the impact of removing `.lib` files that also have `.dll` files and the size reduction is likely to be much smaller, I'll just leave those in the package for now.

**Comment by ocefpaf** [comment]
> he last thing that I might consider doing is to optimize the size of the new Windows packages.

Awesome! I'm OK with your strategy here. Just let me know if you want me to merge this or feel free to self-merge it once you are done.

**Comment by RobinD42** [comment]
The wxWidgets .lib files are the "import libs" for the .DLLs, basically a list of symbol names and offsets within the corresponding DLL. So, although there are other ways to do it, including the .lib files means it would be easier to link with those .DLLs when others are building code that uses wxWidgets.

**Comment by timsnyder** [comment]
> including the .lib files means it would be easier to link with those .DLLs when others are building code that uses wxWidgets.
Thanks @RobinD42.  I had a suspicion that might be the case.  I've removed the `.pdb` files and that cut the package size by more than half.  Will leave all the `.lib` files included.  Unless you'd like more time to review the build changes I've made, I'll go ahead and merge once all of the CI is clean.

**Comment by RobinD42** [comment]
Looks good to me.

**Pull request merged**
